### ISSUE TITLE
UIFont not support bold style

### ISSUE THREAD

**Issue by thuai** [ClassyKit/Classy#102]
I want to get a bold UIFont object.
Here is my code.

```
UILabe {
font bold 20
}
```

I can't work. I've saw the source, it looks like not support **bold**.

Anyone know how to get a bold font?
Thanks very much!

**Comment by ArtFeel** [comment]
Try this

```
UILabel {
  font HelveticaNeue-Bold 20;
}
```

**Comment by dnedrow** [comment]
@thuai , I've verified that @ArtFeel has provided the correct answer. Can we close this issue?

**Comment by thuai** [comment]
@dnedrow @ArtFeel  Thanks. That works for me.
