### ISSUE TITLE
XCode Plugin + Autocomplete

### ISSUE THREAD

**Issue by calimarkus** [ClassyKit/Classy#11]
That would help a lot in writing the specs / cas files!

Example: https://github.com/ricobeck/KFCocoaPodsPlugin

Great tool. Thanks.

**Comment by keithnorm** [comment]
I started writing a langspec for Classy here https://github.com/keithnorm/Classy-langspec/

It's better than nothing, but it still needs a bunch of improvements. Mainly I haven't been able to figure out how to make the xcode lexer understand properties like background-image[state:normal] yet (it loses syntax highlighting for those styles) and I'm not sure if the keyword list includes all possible properties (in fact I'm sure it doesn't, so it won't autocomplete for some values). But it has been helpful to me, check it out if you'd like!

**Comment by dnedrow** [comment]
Added @keithnorm langspec to wiki.
