### ISSUE TITLE
Comparison with Pixate Freestyle

### ISSUE THREAD

**Issue by aidansteele** [ClassyKit/Classy#47]
I've previously used the Pixate framework, but got very excited by Classy's development due to its open-source nature. In my mind, Classy's primary competitive advantage is (was) the fact that it was open source: if there was a bug, I could fix it myself and not be dependent on upstream (not that it's been a problem yet!)

It seems that a [couple of weeks ago](http://www.pixate.com/blog/2014-02-19-pixate-freestyle/index.html) Pixate went open source and is now available on Github: https://github.com/pixate/pixate-freestyle-ios 

Users will now be comparing Pixate and Classy directly. Perhaps a list of pros and cons for Classy vs Pixate in the README would be useful? What are your thoughts?

EDIT: Perhaps a comparison to NUI would be useful too?: https://github.com/tombenner/nui

**Comment by WhitneyLand** [comment]
Late to comment, but can someone say why custom selectors are needed in Classy?  For example UIControl { } and ^UIControl { }, why couldn't these be done fairly simple in plain old CSS?
