### ISSUE TITLE
Support CSS' :nth-child pseudo-class

### ISSUE THREAD

**Issue by aidansteele** [ClassyKit/Classy#48]
One neat feature that the-other-styling-framework (:smile:) has is support for CSS's `:nth-child` pseudo-class. It comes in particularly handy for e.g. when giving alternating background colours to `UITableViewCell`.

What I am currently doing is something like

``` objc
- (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath;
{
  Subclass *c = (Subclass *)cell;
  [cell setBackgroundColor:[indexPath row] % 2 ? [c firstColor] : [c secondColor]];
}
```

And the stylesheet has:

``` css
Subclass {
    first-color: #fff;
    second-color: #ddd;
}
```

It'd be great if there was a better way to do this!

**Comment by dnedrow** [comment]
@keithnorm comment added to wiki.
