### ISSUE TITLE
Why does cas_updateStyling check for self.window?

### ISSUE THREAD

**Issue by knopp** [ClassyKit/Classy#64]
We need to get certain styled properties before the hierarchy is complete. To do that I manually call cas_updateStyling on view when I know that the hierarchy is deep enough for the proper styles to get applied. This no longer works because cas_updateStyling in UIView+CASAddtions checks for self.window, which is nil at that point. Why does it do the check?

**Comment by dnedrow** [comment]
@knopp Can this issue be closed?

**Comment by dnedrow** [comment]
Added two the wiki.
