### ISSUE TITLE
Changing component style at runtime and in animation

### ISSUE THREAD

**Issue by denislutz** [ClassyKit/Classy#65]
Hi cloudkite, 

I love classy, thank you for this awesome framework.

Changing a style class at runtime is very known from web applications. Like expand collapse cases for example.

Question:
Example use case.
I want to add some class on a button after it was clicked.
So in my View I do something like that:

[self.myButton cas_addStyleClass:@"expanded"];

Then I remove the style class if its clicked again.
[self.myButton cas_removeStyleClass:@"expanded"];

Is that a feasible way to use classy? 
Do I need to call something else to update the view hierarchy?
While that in general works, it is not supporting any animations inside the animation block.
[UIView animateWithDuration:defaultAnimationDuration
                         animations:^{
So I dont know what exactly I need to do to perform this style class change as an animation.

**Comment by dnedrow** [comment]
@denislutz , can this issue be closed?

**Comment by denislutz** [comment]
yes, thx.

**Comment by dnedrow** [comment]
@denislutz Added the animation information to a new how-to section of the wiki. Closing the issue per questioner.
