### ISSUE TITLE
Loading images from remote URLs

### ISSUE THREAD

**Issue by daniel-hall** [ClassyKit/Classy#69]
Hi!  Really like what you're doing with Classy, and I'm exploring its suitability for a large project I'm working on.  One requirement this project has is the ability to load icons and images for styled elements from a URL, as opposed to only using resources in the app's bundle.

In Pixate / CSS, doing this works something like:

.myClass {
   background-image: url("http://somewhere.com/images/icon.png");
}

Is there a similar functionality implemented or planned for Classy?

**Comment by dnedrow** [comment]
@daniel-hall , can this issue be closed?

**Comment by dnedrow** [comment]
Added information to wiki how-to.
