### ISSUE TITLE
Feature request:  array values

### ISSUE THREAD

**Issue by daniel-hall** [ClassyKit/Classy#70]
I'd like to request support for array values in styles.  Specifically, this is to enable setting array of colors and locations on a CAGradientLayer within a custom view class.  I imagine there might be other uses as well in other custom subclass scenarios.

This might look something like:

MyCustomView {
     gradientLayer: @ {
          colors: [red, rgb(160, 180, 220), green]
          locations: [0.0, 0.2, 1.0]
     }
}

**Comment by dnedrow** [comment]
Added to wiki wish list.
