### ISSUE TITLE
Classy doesn't seem to find properties added through categories

### ISSUE THREAD

**Issue by doubleedan** [ClassyKit/Classy#73]
Hi there,

When I add properties to UIView via a category, and then target those properties through a style sheet, nothing happens.  It seems like Classy's reflection doesn't find properties added through extensions?  Is there a workaround - or am I misdiagnosing this issue?

Thanks.

**Comment by dnedrow** [comment]
@doubleedan , can this issue be closed?

**Comment by dnedrow** [comment]
Added info to wiki how-to.
