### ISSUE TITLE
FEATURE REQUEST: Dynamic typefaces

### ISSUE THREAD

**Issue by peymankh** [ClassyKit/Classy#74]
I'm at the stage of evaluating Classy to use for my project. It seems like a brilliant solution and given the fact that it's done by @cloudkite, the creator of Masonry, I'm being more and more encouraged to use this for my project as well.

There are a few issues which I'll post in separately which I'll think would be great improvements to this project.

As for this specific issue, Apple added dynamic type faces to their API in iOS 7 and seems like, a lot of apps are vastly using it. Using NSNotificationCenter in every controller to update the typefaces seems a bit hideous and if we're already using classy to set all the labels, textfields and buttons font in our apps, it seems to me that having that as a feature in Classy sounds like a better solution.

@cloudkite, would this be something that we can count on in the upcoming releases of Classy? 

Would appreciate your feedback on this.

Thanks.

**Comment by dzindra** [comment]
See #89

**Comment by dnedrow** [comment]
@peymankh , given the contribution by @dzindra, Classy supports dynamic fonts. Can this issue be closed?

**Comment by dnedrow** [comment]
Closing as Dynamic Type is now supported out of the box.
