### ISSUE TITLE
May my application reject due swizzling in your library

### ISSUE THREAD

**Issue by Ikimura** [ClassyKit/Classy#79]
Hello

First of all, thank you for your great work

You are using swizzling(method cas_swizzleInstanceSelector) in your lib as I found .
May I have any troubles with Apple due it

**Comment by dnedrow** [comment]
@Ikimura , are you satisfied with the answers given? If so, can you close this issue?

**Comment by dnedrow** [comment]
See [Issue #119](https://github.com/ClassyKit/Classy/issues/119)
