### ISSUE TITLE
problem with style not being correctly applied after dismissViewControllerAnimated:completion

### ISSUE THREAD

**Issue by latteier** [ClassyKit/Classy#80]
I'm having a problem with styles applied via properties not working when a view is re-displayed.

I define a default font for UILabels within a view controller and override this setting for the subjectLabel.

```
MyTableViewController {
  UILabel {
    font: $smaller
  }
  subjectLabel @{
    font: $larger
  }
}
```

This works fine. But when I present a view controller, and later dismiss it and return back to this view, the settings for the subjectLabel aren't used -- it uses the default UILabel settings.

If I change to using a cas_styleClass selector rather than a property selector everything works correctly.

Thanks for your help!

**Comment by XUJiahua** [comment]
I got this issue either

**Comment by dnedrow** [comment]
@latteier Did you ever resolve this? Did you try placing the call to cas_updateStyling in the completion block of dismissViewControllerAnimated?

**Comment by dnedrow** [comment]
@latteier , please close this issue if it no longer applies.

**Comment by latteier** [comment]
Probably best to close this. I haven't looked at this stuff in a long time.
