### ISSUE TITLE
Defining a color with variable and alpha

### ISSUE THREAD

**Issue by binyamg** [ClassyKit/Classy#86]
- Is it possible to define a color using another color variable and attaching a new alpha value? For example, if we have $base-color, can we say rgba($base-color, 0.75)? $base-color being a hex or rgb value.

**Comment by keithnorm** [comment]
Seems like a great idea but it is not currently supported. Want to take a crack at implementing it? I think it would be cool to have `darken` and `lighten` functions to act on a base color as well.

Imagine a use-case like:

```
UIButton {
  background-color[state: normal]: $blue
  background-color[state: highlighted]: lighten($blue, 20%)
}
```

I may get around to adding that functionality.

**Comment by dnedrow** [comment]
@keithnorm , what does the 20% value represent? An alpha percentage increase/decrease? If so, would it take into account the current alpha of the color. Eg., blue with an alpha of 0.8, after lighten($blue, 20%) would end up with an alpha of 0.64?

**Comment by dnedrow** [comment]
Added to wiki wish list.
